server:
  # 开发环境端口
  port: 8201

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ssyx-acl?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

  jackson:
    # 时间格式
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8